//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by SamplePro.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_SAMPLEPRO_DIALOG            102
#define IDS_SELECT_TITTLE               102
#define IDR_MAINFRAME                   128
#define IDD_DLG_CTL                     129
#define IDD_DLG_PICVIEW                 130
#define IDD_DLG_ROISET                  131
#define IDC_CURSOR1                     132
#define IDC_CURSOR2                     133
#define IDC_CURSOR3                     134
#define IDC_CURSOR4                     135
#define IDC_CURSOR5                     137
#define IDC_CURSOR6                     138
#define IDD_DIALOG2                     139
#define IDD_DLG_COMPRESS                139
#define IDD_DLG_INF                     142
#define IDD_DLG_CAMCONTROL              143
#define IDD_DLG_IMACAPTURE              144
#define IDD_DLG_ROI                     145
#define IDD_DLG_TRIGER                  146
#define IDD_DLG_MOREPARA                147
#define IDD_DLG_CLRCONTROL              148
#define IDD_DLG_OTHER                   149
#define IDD_DLGRAM                      150
#define IDS_DLG_INF                     318
#define IDS_DLG_CAMCON                  319
#define IDS_DLG_IMACAP                  320
#define IDS_DLG_CLRC                    321
#define IDS_DLG_MOREPAR                 322
#define IDS_DLG_ROI                     323
#define IDS_DLG_TRIG                    324
#define IDS_DLG_OTHER                   325
#define IDC_STA_PIC                     1000
#define IDC_STA_INFO                    1001
#define IDC_STA_CAMERACTL               1002
#define IDC_COMBO1                      1003
#define IDC_CMB_RES                     1003
#define IDC_BUTTON1                     1004
#define IDC_BTN_LIVE                    1004
#define IDC_BTN_RAM                     1004
#define IDC_BTN_INFO                    1004
#define IDC_STA_IMGCAPTURE              1005
#define IDC_BTN_ControlControl          1005
#define IDC_SPN_MIN                     1006
#define IDC_BTN_CCN2                    1006
#define IDC_BTN_Other                   1006
#define IDC_EDT_MIN                     1007
#define IDC_BTN_ImageCapture            1007
#define IDC_BUTTON2                     1008
#define IDC_BTN_EXPTM                   1008
#define IDC_BTN_Trigger                 1008
#define IDC_EDT_SEC                     1009
#define IDC_BTN_ColorControl            1009
#define IDC_EDT_MS                      1010
#define IDC_BTN_MorePara                1010
#define IDC_EDT_US                      1011
#define IDC_SPN_US                      1012
#define IDC_SPN_MS                      1013
#define IDC_SPN_SEC                     1014
#define IDC_BUTTON3                     1015
#define IDC_BTN_CAPTURE                 1015
#define IDC_BTN_BB                      1015
#define IDC_BTN_W                       1015
#define IDC_EDT_PATH                    1016
#define IDC_BUTTON4                     1017
#define IDC_BTN_BROWSE                  1017
#define IDC_BTN_ONCEAE                  1017
#define IDC_EDIT7                       1018
#define IDC_EDT_PICNAME                 1018
#define IDC_CHECK1                      1019
#define IDC_CHK_USETIME                 1019
#define IDC_CHK_DPC_OFF                 1019
#define IDC_EDIT8                       1020
#define IDC_EDTPICNUM                   1020
#define IDC_EDT_PICNUM                  1020
#define IDC_CHK_DPC_LOW                 1020
#define IDC_CHECK2                      1021
#define IDC_CHK_TIF                     1021
#define IDC_CHK_DPC_MED                 1021
#define IDC_CHECK3                      1022
#define IDC_CHK_RAW                     1022
#define IDC_CHK_DPC_HIGH                1022
#define IDC_CHECK4                      1023
#define IDC_CHK_JPG                     1023
#define IDC_CHK_AB                      1023
#define IDC_CHECK5                      1024
#define IDC_CHK_PNG                     1024
#define IDC_STA_MIN                     1025
#define IDC_STA_SEC                     1026
#define IDC_STA_MS                      1027
#define IDC_STA_US                      1028
#define IDC_STA_PARAMETERS              1029
#define IDC_ST_                         1030
#define IDC_STA_TRIGGER                 1030
#define IDC_CHK_ROI                     1031
#define IDC_RADIO_HDR                   1032
#define IDC_RADIO_HIGHTGAIN             1033
#define IDC_RADIO_HIGHGAIN              1033
#define IDC_RADIO_LOWGAIN               1034
#define IDC_CHk_HFLIP                   1035
#define IDC_CHK_AUTOLEVEL               1036
#define IDC_CHK_VFLIP                   1037
#define IDC_SLIDER_LL                   1038
#define IDC_SLD_LLEVEL                  1038
#define IDC_SLIDER_CL                   1039
#define IDC_SLD_COOL                    1039
#define IDC_SLIDER_LR                   1040
#define IDC_SLD_RLEVEL                  1040
#define IDC_STA_ROI                     1041
#define IDC_SLD_GAMM                    1041
#define IDC_SLIDER_DELAY                1042
#define IDC_SLD_RCHN                    1042
#define IDC_SLIDER_FRAME                1043
#define IDC_SLD_SHARP                   1043
#define IDC_COM_CURTEMP                 1044
#define IDC_RADIO_OFF                   1045
#define IDC_SLD_BCHN                    1045
#define IDC_EDT_CL                      1046
#define IDC_EDT_COOL                    1046
#define IDC_EDT_LR                      1047
#define IDC_EDT_RLEVEL                  1047
#define IDC_EDT_LL                      1048
#define IDC_EDT_LLEVEL                  1048
#define IDC_RADIO_STANDARD              1049
#define IDC_SLD_SAT                     1049
#define IDC_RADIO_SYNCHRO               1050
#define IDC_SLD_CLRTEMP                 1050
#define IDC_CHK_STTRIGGER               1051
#define IDC_EDT_DELAY                   1052
#define IDC_EDT_FRAME                   1053
#define IDC_BTN_SNAP                    1054
#define IDC_BTN_UPDATE                  1055
#define IDC_BTN_DEFAULT                 1056
#define IDC_STA_CAMERA                  1057
#define IDC_RADIO_GLOABAL               1058
#define IDC_RADIO_TIMED                 1059
#define IDC_RADIO_WIDTH                 1060
#define IDC_RADIO_RISING                1061
#define IDC_RADIO_FALLING               1062
#define IDC_BTN_APPLY                   1063
#define IDC_STA_SN                      1064
#define IDC_STA_FS                      1065
#define IDC_STA_FW                      1065
#define IDC_STA_USB                     1066
#define IDC_STA_SDKS                    1067
#define IDC_STA_FRAMSPEED               1068
#define IDC_STA_OTHER                   1068
#define IDC_STA_CAPTURE                 1069
#define IDC_STA_LLEVEL                  1070
#define IDC_STA_RLEVEL                  1071
#define IDC_STA_COOL                    1072
#define IDC_STA_FPS                     1073
#define IDC_STA_TEMP                    1074
#define IDC_STA_COLOR                   1075
#define IDC_STA_PICNAME                 1076
#define IDC_STA_CAPMSG                  1077
#define IDC_BTN_OK                      1078
#define IDC_EDT_RGAIN                   1078
#define IDC_STA_TOTAL                   1078
#define IDC_BTN_CANCEL                  1079
#define IDC_EDT_GGAIN                   1079
#define IDC_EDT_HOFFSET                 1080
#define IDC_STA_HOFF                    1081
#define IDC_STA_WIDTH                   1082
#define IDC_STA_HEIGHT                  1083
#define IDC_EDT_WIDTH                   1084
#define IDC_EDT_VOFFSET                 1085
#define IDC_EDT_HEIGHT                  1086
#define IDC_BTN_ROI                     1087
#define IDC_STA_VOFF                    1088
#define IDC_STA_WRSN                    1089
#define IDC_EDT_WRSN                    1090
#define IDC_BTN_WRSN                    1091
#define IDC_BTN_SETTING                 1092
#define IDC_EDT_BGAIN                   1092
#define IDC_COMBO_COMPRESS              1093
#define IDC_EDT_SATURATION              1093
#define IDC_BTN_REC                     1094
#define IDC_BTN_CODEC                   1095
#define IDC_STA_RECTM                   1096
#define IDC_CHK_USETM                   1097
#define IDC_EDIT1                       1098
#define IDC_EDT_RECTM                   1098
#define IDC_EDT_ACTUAL                  1098
#define IDC_EDT_REGADD                  1098
#define IDC_STA_RGAIN                   1099
#define IDC_STA_GGAIN                   1100
#define IDC_STA_BGAIN                   1101
#define IDC_SLD_RGAIN                   1102
#define IDC_SLD_BGAIN                   1103
#define IDC_SLD_GGAIN                   1104
#define IDC_BTN_WB                      1105
#define IDC_STA_SATURATION              1106
#define IDC_SLD_SATURATION              1107
#define IDC_STA_GAMMA                   1108
#define IDC_EDT_GAMMA                   1109
#define IDC_SLD_GAMMA                   1110
#define IDC_STA_SHARP                   1110
#define IDC_EDT_WRSN2                   1111
#define IDC_STA_SHIFT                   1111
#define IDC_STA_RCHN                    1111
#define IDC_SLD_SHIFT                   1112
#define IDC_SLD_GAIN                    1112
#define IDC_STA_BCHN                    1112
#define IDC_EDT_SHIFT                   1113
#define IDC_EDT_GAIN                    1113
#define IDC_EDT_RCHN                    1113
#define IDC_STA_CURTMP                  1114
#define IDC_CHECK6                      1115
#define IDC_CHK_AE                      1115
#define IDC_STA_SAT                     1115
#define IDC_SLD_TGR                     1116
#define IDC_STA_CLRTEMP                 1116
#define IDC_EDT_ATTGR                   1117
#define IDC_BTN_DFC                     1118
#define IDC_CHK_ATWB                    1119
#define IDC_BTN_FFC                     1120
#define IDC_CHK_FFC                     1121
#define IDC_STA_CONTRAST                1122
#define IDC_SLD_CONTRAST                1123
#define IDC_EDT_CONTRAST                1124
#define IDC_CHK_BITOFDEPTH              1125
#define IDC_EDT_CONTRAST2               1125
#define IDC_EDT_SHARP                   1125
#define IDC_CHK_ATL                     1126
#define IDC_CHK_ATR                     1127
#define IDC_STA_CMS                     1128
#define IDC_STA_GCHN                    1128
#define IDC_SLD_SHIFT2                  1129
#define IDC_SLD_CMS                     1129
#define IDC_SLD_GCHN                    1129
#define IDC_EDT_CMS                     1130
#define IDC_EDT_GCHN                    1130
#define IDC_EDIT2                       1131
#define IDC_EDIBLACKLEVEL               1131
#define IDC_EDT_PERCENT                 1131
#define IDC_EDT_BCHN                    1131
#define IDC_EDT_VALUE                   1131
#define IDC_TAB                         1132
#define IDC_EDT_SAT                     1132
#define IDC_CPROGRESS                   1133
#define IDC_EDT_CLRTEMP                 1133
#define IDC_RADIO_TODISK                1134
#define IDC_RADIO_TORAM                 1135
#define IDC_STATIC_RAMINFO              1136
#define IDC_RADIO_ACTUAL                1137
#define IDC_RADIO_PERCENT               1138
#define IDC_SPIN1                       1139
#define IDC_SPN_PERCENT                 1139
#define IDC_SPN_PICNUM                  1139
#define IDC_GRP_EXP                     1141
#define IDC_STA_GAIN                    1142
#define IDC_GROUP_BASIC                 1143
#define IDC_STA_AUTO                    1144
#define IDC_GROUP_DPC                   1145
#define IDC_GROUP_CLRCTRL               1146
#define IDC_GROUP_INFO                  1147
#define IDC_GROUP_CAMCTRL               1148
#define IDC_GROUP_ROI                   1149
#define IDC_STA_REC                     1150
#define IDC_GROUP_Image                 1151
#define IDC_STA_DELAY                   1152
#define IDC_GROUP_TRIGGER               1153
#define IDC_BTN_APLAY                   1154
#define IDC_COMBO_SLAADD                1155
#define IDC_BTN_R                       1156
#define IDC_STA_SA                      1157
#define IDC_STA_REG                     1158
#define IDC_STA_VALUE                   1159
#define IDC_GRP_COM                     1160
#define IDC_RADIO_CMS                   1161
#define IDC_COMBO2                      1162
#define IDC_COM__BITOFDEPTH             1162
#define IDC_STA_MEAN                    1163
#define IDC_STA_MEAN2                   1164
#define IDC_STA_STD                     1164
#define IDC_STA_SNNAME                  1164
#define IDC_STA_FWNAME                  1165
#define IDC_STA_USBNAME                 1166
#define IDC_BUTTON5                     1167
#define IDC_BTN_USBLED                  1167

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        151
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1168
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
